### PR TITLE
Fixes issue with multiple Athena tabular conditions

### LINKED ISSUE #128: Result does not sort correctly with Multiple OrderBy
1. Steps:
        1. Select a component, and enter property group / selected properties / filter. 
        2. Add multiple order by and run query
    2. Error:
        1. Response on the plugin is not sorted based on the order of the OrderBy.
        2. Example add first order as x and second order as Y.
        3. Display on the panel order is based on Y but not on X.
        4. We need to add a logic sort based on the order of the OrderBy.

### PR DESCRIPTION
**Pull request by toddtreece**
fixes #128

### CODE REVIEW

File: pkg/models/query.go [hunk 1]
```diff
@@ -92,30 +93,29 @@ func (f *TwinMakerPropertyFilter) ToTwinMakerFilter() *iottwinmaker.PropertyFilt
...
+	Order        TwinMakerResultOrder `json:"order,omitempty"`
+	PropertyName string               `json:"propertyName,omitempty"`
 }
 
 func (orderBy *TwinMakerOrderBy) ToTwinMakerOrderBy() *iottwinmaker.OrderBy {
-	o := &iottwinmaker.OrderBy{
-		Order: 		  &orderBy.Order,
-		PropertyName: &orderBy.PropertyName,
+	return &iottwinmaker.OrderBy{
+		Order:        aws.String(orderBy.Order),
```
Comment (toddtreece) [inline pkg/models/query.go:103]: @hwandersman this was the main fix in this PR. it's a tricky part of looping with `range` in go: https://github.com/golang/go/discussions/56010

**Review by hwandersman — APPROVED** [review]

File: pkg/plugin/twinmaker/client.go [hunk 2]
```diff
@@ -49,6 +51,15 @@ type twinMakerClient struct {
...
 func NewTwinMakerClient(settings models.TwinMakerDataSourceSetting) (TwinMakerClient, error) {
+	httpClient, err := httpclient.New()
+	if err != nil {
+		return nil, err
+	}
+	transport, err := httpclient.GetTransport()
+	if err != nil {
+		return nil, err
+	}
+	httpClient.Transport = httplogger.NewHTTPLogger("grafana-iot-twinmaker-datasource", transport)
```
Comment (toddtreece) [inline pkg/plugin/twinmaker/client.go:62]: this adds support for [HAR logging](https://github.com/grafana/grafana-plugin-sdk-go/tree/main/experimental/http_logger#http-traffic-logger), which can be useful when debugging.

copy this to your `grafana.ini` to enable and update the `har_log_path`:
```ini
[plugin.grafana-iot-twinmaker-datasource]
har_log_enabled = true
har_log_path = /home/example/twinmaker.har
```

File: pkg/models/query.go [hunk 3]
```diff
@@ -83,7 +84,7 @@ type TwinMakerListEntitiesFilter struct {
 
 func (f *TwinMakerPropertyFilter) ToTwinMakerFilter() *iottwinmaker.PropertyFilter {
 	filter := &iottwinmaker.PropertyFilter{
-		PropertyName: &f.Name,
+		PropertyName: aws.String(f.Name),
```
Comment (toddtreece) [inline pkg/models/query.go:87]: this appears to fix #130
image
