### PR TITLE
Fix template repeat for custom panels

### LINKED ISSUE #109: [Request]: Angle and zoom level predefined
It would be very great to be able to load the 3D view with a predined angle and zoom level defined by a variable in grafana.

### LINKED ISSUE #175: Bug: Video Player does not use the correct value for repeated variable
**What happened**:
When the Video Player Panel is used with a Dashboard Variable, and has the Panel in a Row that repeats by Variable, the Row Name is correct, however the Panel seems to use the "All" Variable and shows all values from the Variable, rather than the individual Variable for that row.

image

note that even though the titles, set as `${System}_CAM1` are correct, the video player interpolation of the value is not:
image

From my initial investigation, the issue seems to be that the video player panel is not getting the correct value to use for `$System`.

**What you expected to happen**:
Its expected that the Repeat Variable should be correctly used in the Video Player like it is in the Title and Row.

**How to reproduce it (as minimally and precisely as possible)**:
Reproduction dashboard: 
```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 433,
  "iteration": 1678290630082,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "collapsed": false,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "panels": [],
      "title": "$System Cameras",
      "type": "row"
    },
    {
      "gridPos": {
        "h": 10,
        "w": 4.8,
        "x": 0,
        "y": 1
      },
      "id": 4,
      "maxPerRow": 6,
      "options": {
        "componentName": "",
        "datasource": "",
        "entityId": "",
        "kvsStreamName": "$System"
      },
      "repeat": "System",
      "repeatDirection": "h",
      "title": "${System}_CAM1",
      "type": "grafana-iot-twinmaker-videoplayer-panel"
    }
  ],
  "schemaVersion": 35,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": false,
          "text": "All",
          "value": "$__all"
        },
        "hide": 0,
        "includeAll": true,
        "multi": false,
        "name": "System",
        "options": [
          {
            "selected": true,
            "text": "All",
            "value": "$__all"
          },
          {
            "selected": false,
            "text": "demo",
            "value": "demo"
          },
          {
            "selected": false,
            "text": "test",
            "value": "test"
          },
          {
            "selected": false,
            "text": "example",
            "value": "example"
          },
          {
            "selected": false,
            "text": "new",
            "value": "new"
          },
          {
            "selected": false,
            "text": "old",
            "value": "old"
          }
        ],
        "query": "demo,test,example,new,old",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "All Cameras",
  "uid": "zkpk9ahVk",
  "version": 2,
  "weekStart": ""
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.4.7
- Plugin version: 8.5.21

### PR DESCRIPTION
**Pull request by hwandersman**
**What this PR does / why we need it**:
When a dashboard has a multi-value template variable in a row that repeats for each value of the variable, each value was not set correctly in a repeated Video Player panel.

The Scene Viewer panel has different types of display options. 3 of these options are for setting the values of certain variables based on a selection in the scene. On load the value of the variables are used to initialize the selection, but it should only be resolved from the URL values. Grafana gives users the ability to save default values which cause issues for the Scene Viewer when deselecting items in the scene. 
1 option is for setting the default active camera which can be resolved by the URL or default dashboard value since it cannot be deselected.

Fixed by [iwysiu](https://github.com/iwysiu)

**Which issue(s) this PR fixes**:

Fixes #175
Fixes #109 

**Special notes for your reviewer**:

### CODE REVIEW

File: src/panels/video-player/VideoPlayer.tsx [hunk 1]
```diff
@@ -30,17 +30,24 @@ export const VideoPlayer = (props: VideoPlayerPropsFromParent) => {
...
   );
 
   // Get display option value from the URL, or check default variable values
   const getDisplayOptionValue = useCallback(
     (queryParams: UrlQueryMap, displayOption: string) => {
-      return (queryParams[getUrlTempVarName(displayOption || '')] as string) ?? checkTempVar(displayOption);
+      const tempVarName = getUrlTempVarName(displayOption || '');
+      const tempVarVal = checkTempVar(displayOption);
+      const tempVarURLVal = queryParams[tempVarName];
+      if (Array.isArray(tempVarURLVal) || tempVarVal !== tempVarURLVal || !(tempVarURLVal as string)) {
```
Comment (iwysiu) [inline src/panels/video-player/VideoPlayer.tsx:46]: I could be misreading this, but if you're returning `tempVarVal` when `tempVarVal !== tempVarURLVal` aren't you  functionally always returning `tempVarVal`?

**Review by iwysiu — COMMENTED** [review]
I ran it and it seems to work! But a question about the logic

File: src/panels/video-player/VideoPlayer.tsx (hunk 1 above)
Comment (hwandersman) [reply src/panels/video-player/VideoPlayer.tsx:46]: You're right I need to reevaluate this

File: src/panels/scene-viewer/SceneViewer.tsx [hunk 2]
```diff
@@ -97,6 +97,33 @@ export const SceneViewer = (props: SceneViewerPropsFromParent) => {
...
+    [replaceVariables]
+  );
+
+  // Get display option value from the URL, or check default variable values
+  const getDisplayOptionValue = useCallback(
+    (queryParams: UrlQueryMap, displayOption: string) => {
+      const tempVarName = getUrlTempVarName(displayOption || '');
+      const tempVarVal = checkTempVar(displayOption);
+      const tempVarURLVal = queryParams[tempVarName];
+      if (Array.isArray(tempVarURLVal) || tempVarVal !== tempVarURLVal || !(tempVarURLVal as string)) {
```
Comment (kevinwcyu) [inline src/panels/scene-viewer/SceneViewer.tsx:119]: `!(tempVarURLVal as string)` can just be `!tempVarURLVal`

File: src/panels/video-player/VideoPlayer.tsx (hunk 1 above)
Comment (kevinwcyu) [reply src/panels/video-player/VideoPlayer.tsx:46]: `!(tempVarURLVal as string)` can just be `!tempVarURLVal`

Comment (hwandersman) [reply src/panels/video-player/VideoPlayer.tsx]: Updated to just use the saved template var value `tempVarVal` as the default, otherwise check the URL for a value.

File: src/panels/video-player/VideoPlayer.tsx [hunk 3]
```diff
@@ -87,9 +90,9 @@ export const VideoPlayer = (props: VideoPlayerPropsFromParent) => {
       // Load in VideoPlayer component
       setVideoData(
         props.appKitTMDataSource.videoData({
-          entityId,
-          componentName,
-          kvsStreamName,
+          entityId: entityId as string,
+          componentName: componentName as string,
+          kvsStreamName: kvsStreamName as string,
```
Comment (kevinwcyu) [inline src/panels/video-player/VideoPlayer.tsx:95]: Can `videoData` handle these arguments if they're arrays or will it throw an error? Since `getDisplayOptionValue` returns a `UrlQueryValue`, it's possible it can also be one of these types `string[] | number[] | boolean[]`. But the `VideoDataProps` type expects only strings.

Some options for removing the type assertions from this file.
1. Update `getDisplayOptionValue` to only ever return a string.
2. Update videoData to support `UrlQueryValue`, and update the type for the displayOptions state like so (the type can be extracted instead of being defined inline if needed)
```tsx
const [displayOptions, setDisplayOptions] = useState<{
    entityId: UrlQueryValue;
    componentName: UrlQueryValue;
    kvsStreamName: UrlQueryValue;
    search: UrlQueryValue;
    startTime: UrlQueryValue;
    endTime: UrlQueryValue;
  }>({
    entityId: '',
    componentName: '',
    kvsStreamName: '',
    search: search,
    startTime: '',
    endTime: '',
  });
```

Comment (hwandersman) [reply src/panels/video-player/VideoPlayer.tsx:95]: I believe `UrlQueryValue` can only be an array if the variable has a value and the string `tempVarVal` would be returned. The only way that `UrlQueryValue` is returned is if some label is in the URL that doesn't match an existing variable in a dashboard. This is possible through the TwinMaker plugin, but we don't support arrays.

Comment (hwandersman) [reply src/panels/video-player/VideoPlayer.tsx]: Updated `getDisplayOptionValue` to return a string. If the type cast gets wonky then there's something wrong with the dashboard setup anyway.

**Review by kevinwcyu — APPROVED** [review]

**Review by iwysiu — APPROVED** [review]
